### ISSUE TITLE
On Mac OS 10.9, gets Can't open ftdi device: FT_DEVICE_NOT_OPENED error, but doesn't on Win7

### ISSUE THREAD

**Issue by zhiwww** [thomaschaaf/node-ftdi#1]
I googled for this issue, found probably because of ftdi_sio (from official Q&A), but the fact is this lib is not installed on my Mac.

What can I do for this?

Thanks.

**Comment by NPellet** [comment]
FYI.

Same issue encountered with Mac OS 10.9 and FT245RL.
Same fix worked like a charm.

You guys are making me happy.
