### ISSUE TITLE
Cannot Open Device

### ISSUE THREAD

**Issue by evantahler** [thomaschaaf/node-ftdi#4]
Hi! I'm on an arm chipset (armv5tejl), and I'm having trouble connecting to my device `FT_DEVICE_NOT_OPENED`.  However, I can see the device listed properly, IE: 
```javascript
[ { description: 'FT232R USB UART',
    serialNumber: 'A603DUGT',
    locationId: 262,
    index: 0,
    vendorId: 0,
    productId: 0 } ]
```

Here's my sample code to reproduce the error:

```javascript
#!/usr/bin/env node

var ftdi = require('ftdi');

var settings = {
  'baudrate': 115200 / 2,
  'databits': 8,
  'stopbits': 2,
  'parity'  : 'none',
};

ftdi.find(function(err, devices){
  console.log(devices)
  device = new ftdi.FtdiDevice(devices[0]);
  device.open(settings, function(){
    //
  });
});
```

I assume that I have the drivers installed properly, or else I wouldn't see the device listed.  Any thoughts?  I can ensure that no other process has the device bound.

**Comment by kilokeith** [comment]
You might have to unload any other drivers first.
```bash
sudo kextunload -bundle-id com.apple.driver.AppleUSBFTDI
sudo kextunload -bundle-id com.FTDI.driver.FTDIUSBSerialDriver
```

**Comment by maxogden** [comment]
@kilokeith running those fixed the issue for me, thanks

**Comment by evantahler** [comment]
Oh! I guess I should close this issue!

Yes, @kilokeith's notes are good ones (OSX added a built-in driver around Yosemite that doesn't quite work right with all devices), and in extreme situations you may also want `cd /System/Library/Extensions && sudo rm -r FTDIUSBSerialDriver.kext`

BTW, this package helped me give one of my favorite presentations: Node for not HTTP: https://github.com/evantahler/node_for_not_http
